// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfzqUeLjZuAb2E205pjv6UBbefn6gDpAA',
    appId: '1:165128879718:web:a48f55d5703d0d4b99f7a7',
    messagingSenderId: '165128879718',
    projectId: 'nfc-project-21b56',
    authDomain: 'nfc-project-21b56.firebaseapp.com',
    databaseURL: 'https://nfc-project-21b56-default-rtdb.firebaseio.com',
    storageBucket: 'nfc-project-21b56.appspot.com',
    measurementId: 'G-MEZEPQSFT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC200DWPWRT2XiiHXnVhtyrTLt-17y5bcY',
    appId: '1:165128879718:android:0cb76396c952406399f7a7',
    messagingSenderId: '165128879718',
    projectId: 'nfc-project-21b56',
    databaseURL: 'https://nfc-project-21b56-default-rtdb.firebaseio.com',
    storageBucket: 'nfc-project-21b56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXSK45P_OQdR9OgkXPMlO7lw_zYt2m2o4',
    appId: '1:165128879718:ios:3fda637daa178fce99f7a7',
    messagingSenderId: '165128879718',
    projectId: 'nfc-project-21b56',
    databaseURL: 'https://nfc-project-21b56-default-rtdb.firebaseio.com',
    storageBucket: 'nfc-project-21b56.appspot.com',
    iosBundleId: 'com.example.nfcApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXSK45P_OQdR9OgkXPMlO7lw_zYt2m2o4',
    appId: '1:165128879718:ios:3fda637daa178fce99f7a7',
    messagingSenderId: '165128879718',
    projectId: 'nfc-project-21b56',
    databaseURL: 'https://nfc-project-21b56-default-rtdb.firebaseio.com',
    storageBucket: 'nfc-project-21b56.appspot.com',
    iosBundleId: 'com.example.nfcApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfzqUeLjZuAb2E205pjv6UBbefn6gDpAA',
    appId: '1:165128879718:web:267172d0db99d25b99f7a7',
    messagingSenderId: '165128879718',
    projectId: 'nfc-project-21b56',
    authDomain: 'nfc-project-21b56.firebaseapp.com',
    databaseURL: 'https://nfc-project-21b56-default-rtdb.firebaseio.com',
    storageBucket: 'nfc-project-21b56.appspot.com',
    measurementId: 'G-3T3V1Q874L',
  );
}
